"""Global HTML postprocess: branding, internal-only links, badge removal, everstart, Lenis."""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parents[1] / "site"
FRAMER_SITE = "6hAkqPku5rwb5w3Hyg2rYY"
PORTFOLIO_FRAMER_SITE = "1J0T6MriCjxl4QdEhZdbYu"

LINK_RE = re.compile(r'href="(https?://[^"]+)"')


def brand_hugo_to_ever(html: str) -> str:
    html = re.sub(r"\bHugoshtar\b", "Ever star", html, flags=re.I)
    html = re.sub(r"\bhugoshtarportfolio\.framer\.website\b", "localhost", html, flags=re.I)
    html = re.sub(r"\bHugo\s+starter\b", "Ever starter", html, flags=re.I)
    html = re.sub(r"\bHugo\s+plus\b", "Ever plus", html, flags=re.I)
    html = re.sub(r"\bHugo\+", "Ever+", html, flags=re.I)
    html = re.sub(r"\bHugo\b", "Ever", html, flags=re.I)
    html = re.sub(r"\bhugo\b", "ever", html)
    html = re.sub(r"\bRebirth Portfolio\b", "EVERSTAR Portfolio", html, flags=re.I)
    html = re.sub(r"Landio\s*-\s*AI Agency\s*&amp;\s*Landing Page Template", "EVERSTAR", html, flags=re.I)
    html = re.sub(r"Landio\s*-\s*AI Agency\s*&\s*Landing Page Template", "EVERSTAR", html, flags=re.I)
    return html


def _keep_external_href(url: str) -> bool:
    if url.startswith("https://framerusercontent.com"):
        return True
    if url.startswith("https://fonts.googleapis.com") or url.startswith("http://fonts.googleapis.com"):
        return True
    if url.startswith("https://fonts.gstatic.com") or url.startswith("http://fonts.gstatic.com"):
        return True
    if url.startswith("https://ga.jspm.io") or url.startswith("http://ga.jspm.io"):
        return True
    return False


def strip_external_hrefs(html: str) -> str:
    def repl(m: re.Match[str]) -> str:
        url = m.group(1)
        if _keep_external_href(url):
            return m.group(0)
        if "127.0.0.1" in url or "localhost" in url:
            return m.group(0)
        if any(
            url.endswith(p)
            for p in (
                "everstart.html",
                "index.html",
                "contact.html",
                "portfolio.html",
                "portfolio-works.html",
                "terms.html",
                "privacy.html",
                "imprint.html",
                "404.html",
            )
        ):
            return m.group(0)
        return 'href="#"'

    return LINK_RE.sub(repl, html)


def remove_framer_badge(html: str) -> str:
    start = html.find('<div id="__framer-badge-container"')
    if start < 0:
        return html
    i = start
    depth = 0
    while i < len(html):
        if html.startswith("<div", i):
            depth += 1
            i += 4
            continue
        if html.startswith("</div>", i):
            depth -= 1
            i += 6
            if depth == 0:
                return html[:start] + html[i:]
            continue
        i += 1
    return html


def remove_framer_editorbar(html: str) -> str:
    # Remove Framer editorbar markup/styles injected into exported pages.
    html = re.sub(
        r"<style>\s*#__framer-editorbar-container.*?</style>",
        "",
        html,
        flags=re.S,
    )
    html = re.sub(
        r"<style>\s*#__framer-editorbar\s*\{.*?</style>",
        "",
        html,
        flags=re.S,
    )
    html = re.sub(
        r'<div id="__framer-editorbar-container".*?</iframe>',
        "",
        html,
        flags=re.S,
    )
    html = re.sub(
        r'<iframe[^>]*id="__framer-editorbar"[^>]*>.*?</iframe>',
        "",
        html,
        flags=re.S,
    )
    return html


def cleanup_saved_page_artifacts(html: str) -> str:
    # Remove broken saved-page assets (like ./terms_files/script).
    html = re.sub(
        r'<script[^>]*src="\./[^"]*_files/script"[^>]*>\s*</script>',
        "",
        html,
        flags=re.S,
    )
    # Remove empty preconnect links generated by export snapshots.
    html = re.sub(
        r'<link rel="preconnect"[^>]*>',
        "",
        html,
        flags=re.S,
    )
    return html


def compact_font_css(html: str) -> str:
    # Replace giant per-page Framer font-face payload with a compact stack.
    replacement = (
        '<style data-framer-font-css="">'
        ':root{--site-font-primary:Inter,"DM Sans","Plus Jakarta Sans",-apple-system,'
        'BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;'
        '--site-font-serif:"Instrument Serif",Georgia,"Times New Roman",serif}'
        "html,body{font-family:var(--site-font-primary);text-rendering:optimizeLegibility;"
        "-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}"
        "</style>"
    )
    return re.sub(
        r'<style data-framer-font-css="">.*?</style>',
        replacement,
        html,
        count=1,
        flags=re.S,
    )


def rewrite_broken_script_main_paths(html: str, site_id: str) -> str:
    return re.sub(
        r'src="\./[^"]*script_main\.([A-Za-z0-9_-]+)\.mjs"',
        rf'src="https://framerusercontent.com/sites/{site_id}/script_main.\1.mjs"',
        html,
    )


def cleanup_external_metadata_and_fonts(html: str) -> str:
    # Remove Framer search-index metadata (external-only).
    html = re.sub(
        r'\s*<meta name="framer-search-index" content="https?://[^"]+">\s*',
        "",
        html,
        flags=re.I,
    )
    html = re.sub(
        r'\s*<meta name="framer-search-index-fallback" content="https?://[^"]+">\s*',
        "",
        html,
        flags=re.I,
    )
    # Remove externally hosted link tags (icons, preconnect, external styles, etc.).
    html = re.sub(
        r'\s*<link(?=[^>]*href="https?://)[^>]*>\s*',
        "",
        html,
        flags=re.I,
    )
    # Remove external font imports; compact_font_css already provides stack.
    html = re.sub(
        r"@import url\(['\"]https?://fonts\.googleapis\.com[^)]+\);?",
        "",
        html,
        flags=re.I,
    )
    # Remove external modulepreload tags; app still boots from script_main.
    html = re.sub(
        r'\s*<link rel="modulepreload"[^>]+href="https?://[^"]+"[^>]*>\s*',
        "",
        html,
        flags=re.I,
    )
    # If srcset points to external hosts, drop it and keep local src.
    html = re.sub(r'\s+srcset="https?://[^"]+"', "", html, flags=re.I)
    return html


def improve_terms_copy(html: str) -> str:
    # Keep structure intact, only polish a known low-quality placeholder line.
    html = html.replace(
        "Terms and conditions are legal agreements between a service provider and a person who wants to use that service.",
        "These Terms and Conditions define the legal agreement between EVERSTAR and every visitor or client using this website and its services.",
    )
    html = html.replace(
        "These Terms and Conditions define the legal agreement between EVERSTAR and every visitor or client using this website and its services.",
        "These Terms and Conditions outline your rights, responsibilities, and acceptable use while accessing EVERSTAR and any related services.",
    )
    html = html.replace(
        "By using this website, you agree to follow these terms and all applicable laws and regulations.",
        "By accessing this website, you agree to these Terms and to all applicable legal and regulatory requirements.",
    )
    return html


def ensure_lenis_smooth(html: str) -> str:
    m = re.search(r"<html([^>]*)\sclass=\"([^\"]*)\"", html)
    if m:
        cls = m.group(2)
        if "lenis-smooth" in cls:
            return html
        if "lenis" in cls:
            cls = cls + " lenis-smooth"
        else:
            cls = "lenis lenis-smooth " + cls
        return html[: m.start(2)] + cls + html[m.end(2) :]
    return re.sub(r"<html([^>]*)>", r'<html\1 class="lenis lenis-smooth">', html, count=1)


def rewrite_to_everstart(html: str) -> str:
    html = html.replace("index.html", "everstart.html")
    return html


def inject_everstar_branding_script(html: str) -> str:
    if "everstar-branding.js" in html:
        return html
    tag = '<script src="./assets/js/everstar-branding.js" defer></script>'
    low = html.lower()
    i = low.rfind("</body>")
    if i >= 0:
        return html[:i] + tag + "\n" + html[i:]
    return html + "\n" + tag


EVERSTAR_META_DESC = (
    "EVERSTAR is the operating layer for ambitious AI SaaS teams—live signals, "
    "unified analytics, and decisions that compound. Clarity without the noise."
)


def upgrade_everstar_meta_description(html: str) -> str:
    if "Supercharge your startup" not in html:
        return html

    def swap(m: re.Match[str]) -> str:
        return m.group(1) + EVERSTAR_META_DESC + m.group(2)

    html = re.sub(
        r'(<meta\s+name="description"\s+content=")[^"]*(")',
        swap,
        html,
        count=1,
        flags=re.I,
    )
    html = re.sub(
        r'(<meta\s+property="og:description"\s+content=")[^"]*(")',
        swap,
        html,
        count=1,
        flags=re.I,
    )
    html = re.sub(
        r'(<meta\s+name="twitter:description"\s+content=")[^"]*(")',
        swap,
        html,
        count=1,
        flags=re.I,
    )
    return html


def inject_everstar_next_layer(html: str) -> str:
    css_tag = '<link rel="stylesheet" href="./assets/css/everstar-next.css">'
    js_tag = '<script src="./assets/js/everstar-next.js" defer></script>'
    low = html.lower()
    if css_tag not in html:
        i = low.rfind("</head>")
        if i >= 0:
            html = html[:i] + "\n\t" + css_tag + "\n" + html[i:]
            low = html.lower()
    if js_tag not in html:
        brand = '<script src="./assets/js/everstar-branding.js" defer></script>'
        if brand in html:
            html = html.replace(brand, js_tag + "\n" + brand, 1)
        else:
            i = low.rfind("</body>")
            if i >= 0:
                html = html[:i] + "\n" + js_tag + "\n" + html[i:]
            else:
                html = html + "\n" + js_tag
    return html


def fix_malformed_portfolio_hrefs(html: str) -> str:
    return html.replace(
        "portfolio.html#everstar-works#selected-projects",
        "portfolio.html#everstar-w-selected-projects",
    )


def postprocess_html(html: str) -> str:
    html = fix_malformed_portfolio_hrefs(html)
    html = brand_hugo_to_ever(html)
    html = rewrite_to_everstart(html)
    html = html.replace('content="index.html"', 'content="everstart.html"')
    html = compact_font_css(html)
    html = rewrite_broken_script_main_paths(html, FRAMER_SITE)
    html = cleanup_saved_page_artifacts(html)
    html = cleanup_external_metadata_and_fonts(html)
    html = strip_external_hrefs(html)
    html = remove_framer_editorbar(html)
    html = remove_framer_badge(html)
    html = ensure_lenis_smooth(html)
    html = improve_terms_copy(html)
    html = upgrade_everstar_meta_description(html)
    html = inject_everstar_branding_script(html)
    html = inject_everstar_next_layer(html)
    return html


def cleanup_legacy_site_files() -> None:
    # Keep a clean, submission-ready site folder with one canonical file per page.
    legacy_files = (
        "main page.html",
        "contacts.html",
        "privicy.html",
        "error page.html",
        "portfolio-works.html",
    )
    for name in legacy_files:
        p = SITE / name
        if p.is_file():
            p.unlink()


def write_redirect_index() -> None:
    (SITE / "index.html").write_text(
        "<!DOCTYPE html><html lang=\"en\"><head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        '<meta http-equiv="refresh" content="0;url=everstart.html">\n'
        '<link rel="canonical" href="everstart.html">\n'
        "<title>EVERSTAR</title>\n"
        "<style>"
        "html,body{min-height:100%;margin:0}"
        "body{display:grid;place-items:center;background:#04070d;color:#e8eef7;"
        "font-family:system-ui,-apple-system,sans-serif;background-image:"
        "radial-gradient(ellipse 80% 60% at 50% -20%,rgba(125,211,252,.12),transparent),"
        "radial-gradient(ellipse 60% 50% at 100% 50%,rgba(167,139,250,.08),transparent)}"
        "a{color:#7dd3fc;text-decoration:none;font-weight:600;border-bottom:1px solid rgba(125,211,252,.4);"
        "padding-bottom:2px;transition:color .2s,border-color .2s}"
        "a:hover{color:#bae6fd;border-bottom-color:#bae6fd}"
        ".w{text-align:center;padding:2rem;max-width:28rem}"
        ".mark{font-size:.75rem;letter-spacing:.28em;text-transform:uppercase;opacity:.55;margin-bottom:1rem}"
        "</style>\n"
        "</head><body><div class=\"w\"><p class=\"mark\">Redirect</p>"
        '<p><a href="everstart.html">Open EVERSTAR</a></p></div>\n'
        "</body></html>",
        encoding="utf-8",
    )


def normalize_title_for_page(html: str, basename: str) -> str:
    titles = {
        "everstart.html": "EVERSTAR",
        "main page.html": "EVERSTAR",
        "portfolio.html": "EVERSTAR — Portfolio",
        "portfolio-works.html": "EVERSTAR — Projects",
        "contact.html": "EVERSTAR — Contact",
        "contacts.html": "EVERSTAR — Contact",
        "terms.html": "EVERSTAR — Terms",
        "privacy.html": "EVERSTAR — Privacy",
        "privicy.html": "EVERSTAR — Privacy",
        "imprint.html": "EVERSTAR — Imprint",
        "404.html": "EVERSTAR — Page not found",
        "error page.html": "EVERSTAR — Page not found",
    }
    title = titles.get(basename)
    if not title:
        return html
    html = re.sub(r"<title>[^<]*</title>", f"<title>{title}</title>", html, count=1, flags=re.I)
    html = re.sub(
        r'<meta\s+property="og:title"\s+content="[^"]*"\s*/?>',
        f'<meta property="og:title" content="{title}">',
        html,
        count=1,
        flags=re.I,
    )
    html = re.sub(
        r'<meta\s+name="twitter:title"\s+content="[^"]*"\s*/?>',
        f'<meta name="twitter:title" content="{title}">',
        html,
        count=1,
        flags=re.I,
    )
    return html


def main() -> None:
    idx = SITE / "index.html"
    if not idx.is_file():
        # Backward-compatible folder names from older exports.
        legacy_main = SITE / "main page.html"
        if legacy_main.is_file():
            main_html = legacy_main.read_text(encoding="utf-8")
            main_html = postprocess_html(main_html)
            main_html = normalize_title_for_page(main_html, "main page.html")
            (SITE / "everstart.html").write_text(main_html, encoding="utf-8")
            write_redirect_index()
            # Keep original file too, but make it the same processed output.
            legacy_main.write_text(main_html, encoding="utf-8")
            for p in SITE.glob("*.html"):
                if p.name in ("index.html", "everstart.html", "main page.html"):
                    continue
                t = p.read_text(encoding="utf-8")
                t = postprocess_html(t)
                t = normalize_title_for_page(t, p.name)
                p.write_text(t, encoding="utf-8")
            return
        raise SystemExit("No site/index.html or site/main page.html — run build_site.py first")
    main_html = idx.read_text(encoding="utf-8")
    ever_path = SITE / "everstart.html"
    if (
        len(main_html) < 12000
        and "everstart.html" in main_html
        and re.search(r'http-equiv\s*=\s*["\']refresh["\']', main_html, re.I)
    ):
        if ever_path.is_file() and len(ever_path.read_text(encoding="utf-8")) > 50000:
            main_html = ever_path.read_text(encoding="utf-8")
        else:
            raise SystemExit(
                "site/index.html is a redirect stub but everstart.html is missing or too small. "
                "Restore a full Framer export as site/index.html, then run this script again "
                "(or run tools/build_site.py when rebirth_portfolio is available)."
            )
    main_html = postprocess_html(main_html)
    main_html = normalize_title_for_page(main_html, "everstart.html")
    (SITE / "everstart.html").write_text(main_html, encoding="utf-8")
    write_redirect_index()

    reb_home = SITE.parent / "sources" / "rebirth" / "home.html"
    ap_script = Path(__file__).resolve().parent / "assemble_portfolio_pages.py"
    if reb_home.is_file() and ap_script.is_file():
        subprocess.run([sys.executable, str(ap_script)], check=False)

    for p in SITE.glob("*.html"):
        if p.name in ("index.html", "everstart.html"):
            continue
        t = p.read_text(encoding="utf-8")
        t = postprocess_html(t)
        t = normalize_title_for_page(t, p.name)
        p.write_text(t, encoding="utf-8")
    cleanup_legacy_site_files()


if __name__ == "__main__":
    main()
